# Generated by Django 5.0 on 2025-10-24 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membresias', '0001_initial'),
        ('promociones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='usuario_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membresias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró'),
        ),
        migrations.AddField(
            model_name='membresiapromocion',
            name='membresia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresias.membresia', verbose_name='Membresía'),
        ),
        migrations.AddField(
            model_name='membresiapromocion',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promociones.promocion', verbose_name='Promoción'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='promociones',
            field=models.ManyToManyField(blank=True, related_name='membresias', through='membresias.MembresiaPromocion', to='promociones.promocion', verbose_name='Promociones Aplicadas'),
        ),
        migrations.AddField(
            model_name='membresia',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='membresias.planmembresia', verbose_name='Plan de Membresía'),
        ),
        migrations.AlterUniqueTogether(
            name='membresiapromocion',
            unique_together={('membresia', 'promocion')},
        ),
    ]
