# Generated by Django 5.0 on 2025-10-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionmembresia',
            name='metodo_de_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('qr', 'Código QR')], max_length=30, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='membresia',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vencido', 'Vencido'), ('suspendido', 'Suspendido')], max_length=20, verbose_name='Estado'),
        ),
    ]
