# Generated by Django 5.0 on 2025-11-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vencido', 'Vencido'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado'),
        ),
    ]
