# Generated by Django 5.0 on 2025-11-25 23:57
# Modificado: La tabla ya existe en productos, solo actualizamos el estado de Django

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),  # Depende de productos porque la tabla ya existe ahí
    ]

    operations = [
        # Separar el estado de Django de la base de datos
        # La tabla ya existe físicamente, solo registramos el modelo en el estado de Django
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No hacemos nada en la BD, la tabla ya existe
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CategoriaProducto',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                        ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                        ('codigo', models.CharField(help_text='Código único de la categoría', max_length=20, unique=True, verbose_name='Código')),
                        ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                        ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                    ],
                    options={
                        'verbose_name': 'Categoría de Producto',
                        'verbose_name_plural': 'Categorías de Productos',
                        'db_table': 'categoria_producto',
                        'ordering': ['nombre'],
                    },
                ),
            ],
        ),
    ]
