# Generated by Django 5.0 on 2025-11-06 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('disciplinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(help_text='Ej: Sala A, Sala Spinning, Sala Yoga', max_length=100, unique=True, verbose_name='Nombre del Salón')),
                ('capacidad', models.PositiveIntegerField(help_text='Número máximo de personas', verbose_name='Capacidad Máxima')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el salón está disponible', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Salón',
                'verbose_name_plural': 'Salones',
                'db_table': 'salon',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha', models.DateField(verbose_name='Fecha de la Clase')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('cupo_maximo', models.PositiveIntegerField(help_text='Número máximo de participantes (basado en capacidad del salón)', verbose_name='Cupo Máximo')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='disciplinas.disciplina', verbose_name='Disciplina')),
                ('instructor', models.ForeignKey(help_text='Usuario con rol de instructor', on_delete=django.db.models.deletion.PROTECT, related_name='clases_instructor', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clases', to='clases.salon', verbose_name='Salón')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clase',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('asistio', 'Asistió'), ('no_asistio', 'No Asistió')], default='confirmada', max_length=20, verbose_name='Estado')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='clases.clase', verbose_name='Clase')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_clases', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Inscripción a Clase',
                'verbose_name_plural': 'Inscripciones a Clases',
                'db_table': 'inscripcion_clase',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
        migrations.AddConstraint(
            model_name='inscripcionclase',
            constraint=models.UniqueConstraint(fields=('clase', 'cliente'), name='unique_cliente_clase'),
        ),
        migrations.AddConstraint(
            model_name='clase',
            constraint=models.UniqueConstraint(fields=('salon', 'fecha', 'hora_inicio'), name='unique_salon_fecha_hora'),
        ),
    ]
