# Generated by Django 5.0 on 2025-10-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Promoción')),
                ('meses', models.IntegerField(help_text='Cantidad de meses que dura la promoción', verbose_name='Meses de Duración')),
                ('descuento', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (ej: 15.00 para 15%)', max_digits=5, verbose_name='Descuento (%)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('VENCIDA', 'Vencida')], default='ACTIVA', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promocion',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
