# Generated by Django 5.0 on 2025-11-07 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('especialidades', models.TextField(help_text='Disciplinas en las que se especializa (ej: Yoga, Spinning, CrossFit)', verbose_name='Especialidades')),
                ('certificaciones', models.TextField(blank=True, help_text='Certificaciones y títulos profesionales', verbose_name='Certificaciones')),
                ('experiencia_anos', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Emergencia')),
                ('biografia', models.TextField(blank=True, help_text='Breve descripción del instructor', verbose_name='Biografía')),
                ('foto_url', models.URLField(blank=True, help_text='URL de la foto de perfil del instructor', verbose_name='URL de Foto')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el instructor está actualmente activo', verbose_name='Activo')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
                'db_table': 'instructor',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario'], name='instructor_usuario_idx'), models.Index(fields=['activo'], name='instructor_activo_idx')],
            },
        ),
    ]
