# Generated by Django 5.0 on 2025-11-24 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('razon_social', models.CharField(help_text='Nombre legal o comercial del proveedor', max_length=200, unique=True, verbose_name='Razón Social')),
                ('nit', models.CharField(help_text='Número de Identificación Tributaria o ID fiscal', max_length=50, unique=True, verbose_name='NIT/ID Fiscal')),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos numéricos.', regex='^\\d{7,15}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator(message='Ingrese un correo electrónico válido.')], verbose_name='Email')),
                ('direccion', models.TextField(blank=True, help_text='Dirección física del proveedor', verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Suspendido')], default='A', max_length=1, verbose_name='Estado')),
                ('contacto_nombre', models.CharField(blank=True, help_text='Persona de contacto en la empresa proveedora', max_length=100, verbose_name='Nombre de Contacto')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales sobre el proveedor', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nit'], name='proveedor_nit_idx'), models.Index(fields=['razon_social'], name='proveedor_razon_idx'), models.Index(fields=['estado'], name='proveedor_estado_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('nit',), name='unique_proveedor_nit'),
        ),
        migrations.AddConstraint(
            model_name='proveedor',
            constraint=models.UniqueConstraint(fields=('razon_social',), name='unique_proveedor_razon_social'),
        ),
    ]
