# Generated by Django 5.0 on 2025-10-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP')),
                ('hora', models.TimeField(verbose_name='Hora')),
            ],
            options={
                'verbose_name': 'Historial de Actividad',
                'verbose_name_plural': 'Historial de Actividades',
                'db_table': 'historial_actividad',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
