# Generated by Django 5.0 on 2025-10-24 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tipo_accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('login_failed', 'Fallo de inicio de sesión'), ('create', 'Crear registro'), ('update', 'Actualizar registro'), ('delete', 'Eliminar registro'), ('create_user', 'Crear usuario'), ('update_user', 'Actualizar usuario'), ('delete_user', 'Eliminar usuario'), ('create_role', 'Crear rol'), ('update_role', 'Actualizar rol'), ('delete_role', 'Eliminar rol'), ('assign_role', 'Asignar rol'), ('remove_role', 'Remover rol'), ('assign_permission', 'Asignar permiso'), ('remove_permission', 'Remover permiso'), ('create_client', 'Crear cliente'), ('update_client', 'Actualizar cliente'), ('delete_client', 'Eliminar cliente'), ('create_membership', 'Crear membresía'), ('update_membership', 'Actualizar membresía'), ('delete_membership', 'Eliminar membresía'), ('subscribe_membership', 'Inscribir a membresía'), ('cancel_membership', 'Cancelar membresía'), ('create_promotion', 'Crear promoción'), ('update_promotion', 'Actualizar promoción'), ('delete_promotion', 'Eliminar promoción'), ('config_change', 'Cambio de configuración'), ('password_reset', 'Restablecimiento de contraseña'), ('error', 'Error del sistema'), ('other', 'Otra acción')], default='other', max_length=50, verbose_name='Tipo de Acción')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('nivel', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='info', max_length=20, verbose_name='Nivel')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP (Legacy)')),
            ],
            options={
                'verbose_name': 'Historial de Actividad',
                'verbose_name_plural': 'Historial de Actividades',
                'db_table': 'historial_actividad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
