# Generated by Django 5.0 on 2025-10-24 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialactividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_actividades', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='historialactividad',
            index=models.Index(fields=['-fecha_hora'], name='historial_a_fecha_h_ec4c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='historialactividad',
            index=models.Index(fields=['usuario', '-fecha_hora'], name='historial_a_usuario_52d30f_idx'),
        ),
        migrations.AddIndex(
            model_name='historialactividad',
            index=models.Index(fields=['tipo_accion', '-fecha_hora'], name='historial_a_tipo_ac_b3fc85_idx'),
        ),
        migrations.AddIndex(
            model_name='historialactividad',
            index=models.Index(fields=['nivel', '-fecha_hora'], name='historial_a_nivel_6cb97d_idx'),
        ),
    ]
