# Generated by Django 5.0 on 2025-10-23 05:45

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialactividad',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Historial de Actividad', 'verbose_name_plural': 'Historial de Actividades'},
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='datos_adicionales',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos Adicionales'),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='nivel',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='info', max_length=20, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='tipo_accion',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('create_user', 'Crear usuario'), ('update_user', 'Actualizar usuario'), ('delete_user', 'Eliminar usuario'), ('create_role', 'Crear rol'), ('update_role', 'Actualizar rol'), ('delete_role', 'Eliminar rol'), ('assign_role', 'Asignar rol'), ('remove_role', 'Remover rol'), ('create_client', 'Crear cliente'), ('update_client', 'Actualizar cliente'), ('delete_client', 'Eliminar cliente'), ('other', 'Otra acción')], default='other', max_length=50, verbose_name='Tipo de Acción'),
        ),
        migrations.AddField(
            model_name='historialactividad',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='historialactividad',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historialactividad',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='historialactividad',
            name='ip',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='IP (Legacy)'),
        ),
        migrations.AddIndex(
            model_name='historialactividad',
            index=models.Index(fields=['-fecha_hora'], name='historial_a_fecha_h_ec4c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='historialactividad',
            index=models.Index(fields=['usuario', '-fecha_hora'], name='historial_a_usuario_52d30f_idx'),
        ),
        migrations.AddIndex(
            model_name='historialactividad',
            index=models.Index(fields=['tipo_accion', '-fecha_hora'], name='historial_a_tipo_ac_b3fc85_idx'),
        ),
        migrations.AddIndex(
            model_name='historialactividad',
            index=models.Index(fields=['nivel', '-fecha_hora'], name='historial_a_nivel_6cb97d_idx'),
        ),
    ]
