# Generated by Django 5.0 on 2025-11-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(help_text='Nombre único de la disciplina (ej: CrossFit, Yoga, Spinning)', max_length=100, unique=True, verbose_name='Nombre de la Disciplina')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la disciplina', null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la disciplina está activa y disponible', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'db_table': 'disciplina',
                'ordering': ['nombre'],
            },
        ),
    ]
