# Generated by Django 5.0 on 2025-10-23 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresia',
            name='inscripcion',
        ),
        migrations.RemoveField(
            model_name='membresia',
            name='usuario_registro',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='client',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='client',
            name='peso',
        ),
        migrations.AddField(
            model_name='client',
            name='ci',
            field=models.CharField(default='00000000', max_length=20, unique=True, verbose_name='Cédula de Identidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 10, 23, 21, 41, 9, 122740, tzinfo=datetime.timezone.utc), verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.DeleteModel(
            name='InscripcionMembresia',
        ),
        migrations.DeleteModel(
            name='Membresia',
        ),
    ]
