# Generated by Django 5.0 on 2025-10-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_membresia_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['ci'], name='cliente_ci_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['telefono'], name='cliente_telefono_idx'),
        ),
    ]
