# Generated by Django 5.0 on 2025-11-25 02:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promociones', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('codigo', models.CharField(help_text='Código único de la categoría', max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'db_table': 'categoria_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(help_text='Nombre comercial del producto', max_length=200, verbose_name='Nombre del Producto')),
                ('codigo', models.CharField(help_text='Código único del producto (puede ser código de barras, SKU, etc.)', max_length=50, unique=True, verbose_name='Código/SKU')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta al público (Bs.)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de adquisición (Bs.) - Opcional', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo')),
                ('stock', models.IntegerField(default=0, help_text='Cantidad disponible en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=0, help_text='Cantidad mínima antes de reorden', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('unidad_medida', models.CharField(choices=[('UNIDAD', 'Unidad'), ('KG', 'Kilogramo'), ('GR', 'Gramo'), ('LB', 'Libra'), ('LITRO', 'Litro'), ('ML', 'Mililitro'), ('CAJA', 'Caja'), ('PAQUETE', 'Paquete')], default='UNIDAD', max_length=20, verbose_name='Unidad de Medida')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('AGOTADO', 'Agotado'), ('DESCONTINUADO', 'Descontinuado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoriaproducto', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('promocion', models.ForeignKey(blank=True, help_text='Promoción vigente aplicable al producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='promociones.promocion', verbose_name='Promoción')),
                ('proveedor', models.ForeignKey(help_text='Proveedor que suministra el producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['codigo'], name='producto_codigo_6cda58_idx'), models.Index(fields=['categoria', 'estado'], name='producto_categor_ec37ac_idx'), models.Index(fields=['proveedor'], name='producto_proveed_a9a260_idx'), models.Index(fields=['estado'], name='producto_estado_a5740b_idx')],
            },
        ),
    ]
