# Generated by Django 5.0 on 2025-11-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_move_categoria_to_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa del producto', null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
