# Generated by Django 5.0 on 2025-11-26 02:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(help_text='Cantidad del movimiento (siempre positivo)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('cantidad_anterior', models.IntegerField(help_text='Stock antes del movimiento', verbose_name='Stock Anterior')),
                ('cantidad_nueva', models.IntegerField(help_text='Stock después del movimiento', verbose_name='Stock Nuevo')),
                ('motivo', models.TextField(help_text='Descripción del motivo del movimiento', verbose_name='Motivo')),
                ('referencia', models.CharField(blank=True, help_text='Número de documento, orden de compra, etc.', max_length=100, verbose_name='Referencia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['producto', '-created_at'], name='movimiento__product_cc878a_idx'), models.Index(fields=['tipo', '-created_at'], name='movimiento__tipo_264429_idx'), models.Index(fields=['usuario', '-created_at'], name='movimiento__usuario_ac7c7f_idx')],
            },
        ),
    ]
