# Generated by Django 5.0 on 2025-11-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del producto (si aplica)', null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
