# Generated by Django 5.0 on 2025-11-07 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
        ('clients', '0002_alter_client_experiencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificado', 'Justificado'), ('tardanza', 'Tardanza')], default='presente', max_length=20, verbose_name='Estado de Asistencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('hora_llegada', models.TimeField(blank=True, help_text='Hora real de llegada del cliente', null=True, verbose_name='Hora de Llegada')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la asistencia', null=True, verbose_name='Observaciones')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clases.clase', verbose_name='Clase')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clients.client', verbose_name='Cliente')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='clases.inscripcionclase', verbose_name='Inscripción')),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró la asistencia (Instructor, Admin, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Asistencia a Clase',
                'verbose_name_plural': 'Asistencias a Clases',
                'db_table': 'asistencia_clase',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['clase', 'fecha_registro'], name='asistencia__clase_i_ec3a5d_idx'), models.Index(fields=['cliente', 'fecha_registro'], name='asistencia__cliente_4903d9_idx'), models.Index(fields=['estado'], name='asistencia__estado_dd3d4d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='asistenciaclase',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'clase'), name='unique_asistencia_inscripcion_clase'),
        ),
    ]
