# Generated by Django 5.0 on 2025-11-26 02:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0003_producto_imagen'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('numero_orden', models.CharField(help_text='Número único de identificación de la orden', max_length=50, unique=True, verbose_name='Número de Orden')),
                ('fecha_orden', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Orden')),
                ('fecha_esperada', models.DateField(blank=True, help_text='Fecha esperada de recepción de la orden', null=True, verbose_name='Fecha Esperada de Entrega')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'db_table': 'orden_compra',
                'ordering': ['-fecha_orden', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de productos a comprar', verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio de compra unitario', max_digits=10, verbose_name='Precio Unitario')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Cantidad × Precio Unitario - Descuento', max_digits=10, verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='productos.producto', verbose_name='Producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.ordencompra', verbose_name='Orden de Compra')),
            ],
            options={
                'verbose_name': 'Item de Orden de Compra',
                'verbose_name_plural': 'Items de Orden de Compra',
                'db_table': 'item_orden_compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['numero_orden'], name='orden_compra_numero_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['fecha_orden'], name='orden_compra_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['estado'], name='orden_compra_estado_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemordencompra',
            unique_together={('orden', 'producto')},
        ),
    ]
